name: Java Build and Deploy to AWS Elastic_beanstalk

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'
          
  deploy: 
    
    runs-on: ubuntu-latest
    needs: build
    steps:
     - name: Download artifact from build job
       uses: actions/download-artifact@v3
       with:
         name: java-app
         
     - name: Deploy to EB
       uses: einaregilsson/beanstalk-deploy@v13
       with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: true
          application_name: testjavaapp
          environment_name: Testjavaapp-env
          version_label: ${{github.SHA}}
          region: us-east-2
          deployment_package: 'hello-world-0.1.0.jar'
          
