name: Java Build and Deploy

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'
          
  deploy:
      runs-on: ubuntu-latest
      needs: build
      
      steps:
      - name: 'Login via Azure CLI'
        uses: Azure/login@v1
        with:
         creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'        
         
      - name: 'Copy application files to Azure VM'
        run: |
          set -exv
          echo "${{ secrets.AZURE_VM_DEPLOY_KEY }}" > deploy_key.pem   
          chmod 600 deploy_key.pem
          scp -o StrictHostKeyChecking=no -i deploy_key.pem -r /${{ github.workspace }}/target/*.jar /etc/nginx/webapp/java.jar
          
